In [1]:
import pandas as pd
import numpy as np
#import warnings
#warnings.filterwarnings("ignore")

In [2]:
# The path to CSV file
file = 'The_Volcanoes_Of_Earth.csv'

In [3]:
# Read volcano data into pandas
df = pd.read_csv(file)
df.head()

,Volcano_Name,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
0,Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",34.5°N,131.6°E,3597.0,9594.0,117805.0,4071152.0
1,Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",23.292°S,67.618°W,0.0,7.0,294.0,9092.0
2,Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",14.501°N,90.876°W,4329.0,60730.0,1042836.0,7634778.0
3,Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",38.537°N,34.621°E,127863.0,127863.0,218469.0,2253483.0
4,Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",46.206°N,121.49°W,0.0,70.0,4019.0,393303.0

In [4]:
# Get a list of all of columns for easy reference
df.columns

Index(['Volcano_Name', 'Volcano_Image', 'Volcano_Type', 'Country', 'Region',
       'Subregion', 'epoch_period', 'Last_Eruption', 'Summit_and_Elevatiuon',
       'Latitude', 'Longitude', 'population_within_5km',
       'population_within_10km', 'population_within_30km',
       'population_within_100km'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2662 entries, 0 to 2661
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Volcano_Name             2662 non-null   object
 1   Volcano_Image            2661 non-null   object
 2   Volcano_Type             2662 non-null   object
 3   Country                  2661 non-null   object
 4   Region                   2661 non-null   object
 5   Subregion                2662 non-null   object
 6   epoch_period             2662 non-null   object
 7   Last_Eruption            2661 non-null   object
 8   Summit_and_Elevatiuon    2661 non-null   object
 9   Latitude                 2661 non-null   object
 10  Longitude                2661 non-null   object
 11  population_within_5km    1467 non-null   float64
 12  population_within_10km   1467 non-null   float64
 13  population_within_30km   1467 non-null   float64
 14  population_within_100km  1467 non-null   float64
dtypes: float64(4), object(11)
memory usage: 312.1+ KB

In [6]:
df.Latitude=df.Latitude.apply(lambda x: "+" + str(x) if "N" in str(x) else "-" + str(x))
df.Longitude=df.Longitude.apply(lambda x: "+" + str(x) if "E" in str(x) else "-" + str(x))
df.head()

,Volcano_Name,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
0,Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",+34.5°N,+131.6°E,3597.0,9594.0,117805.0,4071152.0
1,Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",-23.292°S,-67.618°W,0.0,7.0,294.0,9092.0
2,Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",+14.501°N,-90.876°W,4329.0,60730.0,1042836.0,7634778.0
3,Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",+38.537°N,+34.621°E,127863.0,127863.0,218469.0,2253483.0
4,Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",+46.206°N,-121.49°W,0.0,70.0,4019.0,393303.0

In [7]:
# Remove degree symbol from Latitude and Longitude
df['Latitude'] = df.Latitude.astype(str).str.replace('°N','')
df['Latitude'] = df.Latitude.astype(str).str.replace('°S' , '')
df['Longitude'] = df.Longitude.astype(str).str.replace('°E' , '')
df['Longitude'] = df.Longitude.astype(str).str.replace('°W' , '')
df.head()

,Volcano_Name,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
0,Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",+34.5,+131.6,3597.0,9594.0,117805.0,4071152.0
1,Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",-23.292,-67.618,0.0,7.0,294.0,9092.0
2,Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",+14.501,-90.876,4329.0,60730.0,1042836.0,7634778.0
3,Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",+38.537,+34.621,127863.0,127863.0,218469.0,2253483.0
4,Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",+46.206,-121.49,0.0,70.0,4019.0,393303.0

In [8]:
# Change Latitude and Longidue to a float 
df['Latitude'] = df.Latitude.astype(float)
df['Longitude'] = df.Longitude.astype(float)

In [9]:
df.head()

,Volcano_Name,Volcano_Image,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Summit_and_Elevatiuon,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km
0,Abu,https://volcano.si.edu/gallery/photos/GVP-0895...,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,"641 m, 2103 ft",34.500,131.600,3597.0,9594.0,117805.0,4071152.0
1,Acamarachi,https://volcano.si.edu/gallery/photos/GVP-0688...,Stratovolcano,Chile,South America,"Northern Chile, Bolivia and Argentina",holocene,Unknown - Evidence Credible,"6023 m, 19760 ft",-23.292,-67.618,0.0,7.0,294.0,9092.0
2,Acatenango,https://volcano.si.edu/gallery/photos/GVP-0788...,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,"3976 m, 13045 ft",14.501,-90.876,4329.0,60730.0,1042836.0,7634778.0
3,Acigol-Nevsehir,https://volcano.si.edu/includes/images/noimage...,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,"1683 m, 5522 ft",38.537,34.621,127863.0,127863.0,218469.0,2253483.0
4,Adams,https://volcano.si.edu/gallery/photos/GVP-0281...,Stratovolcano,United States,Canada and Western USA,USA (Washington),holocene,950 CE,"3742 m, 12277 ft",46.206,-121.490,0.0,70.0,4019.0,393303.0

In [10]:
# Split summit and elevation
df[['Summit', 'Elevatiuon']] = df['Summit_and_Elevatiuon'].str.split(',', expand=True)

In [11]:
df['Summit'] = df.Summit.astype(str).str.replace(' m' , '')
df['Summit'] = df.Summit.astype(str).str.strip()
df['Elevatiuon'] = df.Elevatiuon.astype(str).str.replace(' ft' , '')
df['Elevatiuon'] = df.Elevatiuon.astype(str).str.strip()

In [12]:
# Rename column due to misspelling
df.rename(columns = {'Elevatiuon':'Elevation'}, inplace = True)

In [13]:
# Drop null values
cols = ['population_within_5km','population_within_10km','population_within_30km','population_within_100km']
df[cols] = df[cols].replace({'0':np.nan, 0:np.nan})
df2=df.dropna(subset=['population_within_5km','population_within_10km','population_within_30km','population_within_100km'])

In [14]:
# Drop column
df2.drop('Summit_and_Elevatiuon', axis=1,inplace=True)

C:\Users\19722\AppData\Local\Temp\ipykernel_6768\3866703142.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('Summit_and_Elevatiuon', axis=1,inplace=True)

In [15]:
# Drop column
df2.drop('Volcano_Image', axis=1,inplace=True)

C:\Users\19722\AppData\Local\Temp\ipykernel_6768\1619333013.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('Volcano_Image', axis=1,inplace=True)

In [16]:
df2.head()

,Volcano_Name,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km,Summit,Elevation
0,Abu,Shield(s),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,34.500,131.600,3597.0,9594.0,117805.0,4071152.0,641,2103
2,Acatenango,Stratovolcano(es),Guatemala,México and Central America,Guatemala,holocene,1972 CE,14.501,-90.876,4329.0,60730.0,1042836.0,7634778.0,3976,13045
3,Acigol-Nevsehir,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,38.537,34.621,127863.0,127863.0,218469.0,2253483.0,1683,5522
6,Adatarayama,Stratovolcano(es),Japan,"Japan, Taiwan, Marianas",Honshu,holocene,1996 CE,37.647,140.281,428.0,3936.0,717078.0,5024654.0,1728,5669
7,Adwa,Stratovolcano,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,holocene,Unknown - Evidence Credible,10.063,40.831,101.0,485.0,18645.0,1242922.0,1670,5479

In [17]:
df2.isnull().values.any()

False

In [18]:
df2.Volcano_Type.value_counts()

Stratovolcano          388
Stratovolcano(es)       92
Shield                  89
Pyroclastic cone(s)     78
Volcanic field          71
Caldera                 70
Complex                 42
Lava dome(s)            28
Shield(s)               17
Fissure vent(s)         14
Submarine               13
Compound                10
Pyroclastic cone        10
Maar(s)                 10
Tuff cone(s)             8
Lava dome                7
Caldera(s)               7
Pyroclastic shield       6
Crater rows              5
Maar                     4
Fissure vent             3
Unknown                  3
Lava cone                2
Tuff cone                2
Explosion crater(s)      1
Stratovolcano?           1
Subglacial               1
Lava cone(s)             1
Lava cone(es)            1
Tuya                     1
Cone                     1
Name: Volcano_Type, dtype: int64

In [19]:
df2["Volcano_Type"] = df2.Volcano_Type.replace("Stratovolcano(es)", "Stratovolcano")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Pyroclastic cone(s)", "Pyroclastic cone")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava dome(s)", "Lava dome")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Shield(s)", "Shield")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Fissure vent(s)", "Fissure vent")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Maar(s)", "Maar")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Tuff cone(s)", "Tuff cone")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava cone(es)", "Lava cone")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava cone(s)", "Lava cone")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Explosion crater(s)", "Explosion crater")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Stratovolcano?", "Stratovolcano")
df2["Volcano_Type"] = df2.Volcano_Type.replace("Caldera(s)", "Caldera")

df2.Volcano_Type.value_counts()

C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Stratovolcano(es)", "Stratovolcano")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Pyroclastic cone(s)", "Pyroclastic cone")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava dome(s)", "Lava dome")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Shield(s)", "Shield")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Fissure vent(s)", "Fissure vent")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Maar(s)", "Maar")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Tuff cone(s)", "Tuff cone")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava cone(es)", "Lava cone")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Lava cone(s)", "Lava cone")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Explosion crater(s)", "Explosion crater")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Stratovolcano?", "Stratovolcano")
C:\Users\19722\AppData\Local\Temp\ipykernel_6768\312747625.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Volcano_Type"] = df2.Volcano_Type.replace("Caldera(s)", "Caldera")

Stratovolcano         481
Shield                106
Pyroclastic cone       88
Caldera                77
Volcanic field         71
Complex                42
Lava dome              35
Fissure vent           17
Maar                   14
Submarine              13
Compound               10
Tuff cone              10
Pyroclastic shield      6
Crater rows             5
Lava cone               4
Unknown                 3
Explosion crater        1
Subglacial              1
Tuya                    1
Cone                    1
Name: Volcano_Type, dtype: int64

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 986 entries, 0 to 2643
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Volcano_Name             986 non-null    object
 1   Volcano_Type             986 non-null    object
 2   Country                  986 non-null    object
 3   Region                   986 non-null    object
 4   Subregion                986 non-null    object
 5   epoch_period             986 non-null    object
 6   Last_Eruption            986 non-null    object
 7   Latitude                 986 non-null    float64
 8   Longitude                986 non-null    float64
 9   population_within_5km    986 non-null    float64
 10  population_within_10km   986 non-null    float64
 11  population_within_30km   986 non-null    float64
 12  population_within_100km  986 non-null    float64
 13  Summit                   986 non-null    object
 14  Elevation                986 non-null    object
dtypes: float64(6), object(9)
memory usage: 123.2+ KB

In [21]:
df2.epoch_period.value_counts()

holocene       899
pleistocene     87
Name: epoch_period, dtype: int64

In [22]:
#Sunburst chart of rei
df2.Region.value_counts()

South America                     141
Indonesia                         124
México and Central America        103
Africa and Red Sea                103
Japan, Taiwan, Marianas            90
Volcanic Region                    87
Melanesia and Australia            63
Philippines and SE Asia            44
Mediterranean and Western Asia     37
Canada and Western USA             36
Middle East and Indian Ocean       30
Kamchatka and Mainland Asia        27
New Zealand to Fiji                27
Atlantic Ocean                     20
Kuril Islands                      19
West Indies                        15
Iceland and Arctic Ocean           12
Hawaii and Pacific Ocean            6
Alaska                              2
Name: Region, dtype: int64

In [23]:
df2.head()

,Volcano_Name,Volcano_Type,Country,Region,Subregion,epoch_period,Last_Eruption,Latitude,Longitude,population_within_5km,population_within_10km,population_within_30km,population_within_100km,Summit,Elevation
0,Abu,Shield,Japan,"Japan, Taiwan, Marianas",Honshu,holocene,6850 BCE,34.500,131.600,3597.0,9594.0,117805.0,4071152.0,641,2103
2,Acatenango,Stratovolcano,Guatemala,México and Central America,Guatemala,holocene,1972 CE,14.501,-90.876,4329.0,60730.0,1042836.0,7634778.0,3976,13045
3,Acigol-Nevsehir,Caldera,Turkey,Mediterranean and Western Asia,Turkey,holocene,2080 BCE,38.537,34.621,127863.0,127863.0,218469.0,2253483.0,1683,5522
6,Adatarayama,Stratovolcano,Japan,"Japan, Taiwan, Marianas",Honshu,holocene,1996 CE,37.647,140.281,428.0,3936.0,717078.0,5024654.0,1728,5669
7,Adwa,Stratovolcano,Ethiopia,Africa and Red Sea,Africa (northeastern) and Red Sea,holocene,Unknown - Evidence Credible,10.063,40.831,101.0,485.0,18645.0,1242922.0,1670,5479

In [24]:
#Tool tip for map
df2.Last_Eruption.value_counts()

Unknown - Evidence Credible     221
Pleistocene                      87
Unknown - Evidence Uncertain     76
2022 CE                          39
Unknown - Unrest / Holocene      29
                               ...
1898 CE                           1
560 CE                            1
1824 CE                           1
930 BCE                           1
6850 BCE                          1
Name: Last_Eruption, Length: 328, dtype: int64

In [25]:
#Map - Region and epoch, circles, radius = pop per 100, color elev.

In [26]:
df2.loc[df2.epoch_period == "pleistocene"].Volcano_Type.value_counts()

Stratovolcano       31
Shield              20
Volcanic field       7
Pyroclastic cone     6
Lava dome            5
Caldera              5
Submarine            4
Unknown              3
Compound             1
Fissure vent         1
Tuya                 1
Lava cone            1
Maar                 1
Cone                 1
Name: Volcano_Type, dtype: int64

In [27]:
df2.Latitude.value_counts().sum()

986

In [30]:
#df2.to_csv("Vol_clean.csv")

In [31]:
df2.to_json("Vol_clean.json", orient="index")